server:
    servlet:
        context-path: /demo
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&&serverTimezone=GMT
        username: root
        password:
        type: com.alibaba.druid.pool.DruidDataSource     #数据库连接池
        druid:
            initial-size: 5  # 初始化大小
            min-idle: 10
            max-active: 20
            max-wait: 60000
            validation-query: SELECT 1
            test-on-borrow: true
            #中请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
            test-while-idle: true
            #申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连技
            test-on-return: false
             #归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能

# springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
api-docs:
    path: /v3/api-docs
group-configs:
    -group: 'default'
    paths-to-match:  '/***'
packages-to-scan: com.example.demo.controller
#knife4j的增强配置，不需要增强可以不配
knife4j:
    enable: true
    setting:
    language: zh_cn
    swagger-model-name: 实体类列表

mybatis-plus:
    configuration:
    #MyBatis配置开启驼峰功能
        map-underscore-to-camel-case: true
        Log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #为MyBatis引用的实体类自定义别名
    type-aliases-package: com.example.demo.entity