server:
    servlet:
        context-path: /demo
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&&serverTimezone=GMT
        username: root
        password:
        type: com.alibaba.druid.pool.DruidDataSource     #数据库连接池
        druid:
            initial-size: 5  # 初始化大小
            min-idle: 10
            max-active: 20
            max-wait: 60000
            validation-query: SELECT 1
            test-on-borrow: true
            #中请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
            test-while-idle: true
            #申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连技
            test-on-return: false
             #归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能